name: Continuous Integration (CI)

on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    # 1. Скачиваем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 2. Настраиваем .NET SDK для сборки HardwareWrapper (Native AOT)
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Укажи свою версию .NET (8.0 или 9.0)

    # 3. Добавляем MSVC (C++ компилятор) в PATH
    - name: Setup MSVC developer command prompt
      uses: ilammy/msvc-dev-cmd@v1

    # 4. Собираем C# Native AOT библиотеку
    - name: Build HardwareWrapper (C# Native AOT)
      run: |
        cd HardwareWrapper
        dotnet publish -c Release -r win-x64

# 1. Скачиваем и настраиваем Qt6
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.2'          # Укажи нужную версию Qt
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        
    # 2. Устанавливаем C++ библиотеки (crow, spdlog и т.д.)
    - name: Install C++ dependencies via vcpkg
      run: |
        & "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe" install crow:x64-windows spdlog:x64-windows

    # 3. Собираем проект
    - name: Build C++ Backend & Frontend
      run: |
        $vcpkgTargets = "$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\msbuild\vcpkg.targets"
        msbuild SystemMonitor.sln /p:Configuration=Release /p:Platform=x64 "/p:ForceImportBeforeCppTargets=$vcpkgTargets"
